name: Compiling and checking tests

on:
  push:
   
jobs:
  ubuntu-build:
    name    : Ubuntu Build
    runs-on : ubuntu-latest
    steps:
      - name : Checkout code
        uses : actions/checkout@v3

      - name : Install Dependencies
        run  : |
                sudo apt-get update 
                sudo apt-get install cppcheck 
                sudo apt-get install libsdl2-dev
                sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
                git clone https://github.com/ProfesseurPoire/corgi-test -b main
                cd corgi-test
                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=DEBUG
                sudo make install 
                cd ../..
                git clone https://github.com/ProfesseurPoire/corgi-math -b develop
                cd corgi-math
                mkdir build 
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=DEBUG
                sudo make install 

      - name : Run CMake
        run  : |
               export CC=gcc-10 
               export CXX=g++-10 
               mkdir build  
               cd build 
               cmake .. -DCMAKE_BUILD_TYPE=Debug 

      - name : Build Project
        run  : cd build  && make 

      - name : Run Cppcheck
        run  : cppcheck --force ./ -ibuild/
